services:
  mariadb:
    restart: "no"
    ports: !reset []
    volumes: !reset []
    tmpfs:
      - /var/lib/mysql

  redis:
    restart: "no"
    ports: !reset []
    volumes: !reset []
    tmpfs:
      - /data

  kafka:
    restart: "no"
    ports: !reset []
    volumes: !reset []
    tmpfs:
      - /tmp/kraft-combined-logs

  eureka-server:
    image: "${CI_PROJECT_NAME:-erpmsa-ci}/eureka-server:${BUILD_NUMBER:-local}"
    restart: "no"
    ports: !reset []

  account-service:
    image: "${CI_PROJECT_NAME:-erpmsa-ci}/account-service:${BUILD_NUMBER:-local}"
    restart: "no"
    ports: !reset []

  audit-service:
    image: "${CI_PROJECT_NAME:-erpmsa-ci}/audit-service:${BUILD_NUMBER:-local}"
    restart: "no"
    ports: !reset []

  item-service:
    image: "${CI_PROJECT_NAME:-erpmsa-ci}/item-service:${BUILD_NUMBER:-local}"
    restart: "no"
    ports: !reset []

  inventory-service:
    image: "${CI_PROJECT_NAME:-erpmsa-ci}/inventory-service:${BUILD_NUMBER:-local}"
    restart: "no"
    ports: !reset []

  gateway-server:
    image: "${CI_PROJECT_NAME:-erpmsa-ci}/gateway-server:${BUILD_NUMBER:-local}"
    restart: "no"
    ports: !reset []

  prometheus:
    image: "${CI_PROJECT_NAME:-erpmsa-ci}/prometheus:${BUILD_NUMBER:-local}"
    restart: "no"
    ports: !reset []

  grafana:
    image: "${CI_PROJECT_NAME:-erpmsa-ci}/grafana:${BUILD_NUMBER:-local}"
    restart: "no"
    ports: !reset []

volumes:
  mariadb-data:
    name: "${CI_PROJECT_NAME:-erpmsa-ci}-mariadb-data"

  redis-data:
    name: "${CI_PROJECT_NAME:-erpmsa-ci}-redis-data"

  kafka-data:
    name: "${CI_PROJECT_NAME:-erpmsa-ci}-kafka-data"

  prometheus-data:
    name: "${CI_PROJECT_NAME:-erpmsa-ci}-prometheus-data"

  grafana-data:
    name: "${CI_PROJECT_NAME:-erpmsa-ci}-grafana-data"
