spring:
  application:
    name: gatewayServer
  threads:
    virtual:
      enabled: true # Tomcat 기반의 동기 처리를 극대화하는 가상 스레드 활성화
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: Account-service
            uri: lb://AccountService #Eureka 서비스에 등록된 이름만 사용 가능 -> 같은 컴퓨터는 가능
            #uri: http://localhost:7001 # .before(uri("http://localhost:7001"))
            predicates:
              - Path=/account/**         # .GET("/users/**")
            filters:
              - AddRequestHeader=X-Gateway-Request, true
              - AddResponseHeader=X-Gateway-Response, true
          #filters:
          #- StripPrefix=1 mapping하는 네이미을 같이하기에 안씀   # .before(stripPrefix(1))매핑
          - id: item-service
            uri: lb://ITEMSERVICE
            predicates:
              - Path=/items/**
          #            filters:
          #              - StripPrefix=1
          - id: order-service
            uri: lb://ORDERSERVICE
            predicates:
              - Path=/orders/**
#            filters:
#              - StripPrefix=1


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_DEFAULT_ZONE:http://127.0.0.1:8761/eureka}"

server:
  port: "${GATEWAY_SERVER_PORT:7070}"


app:
  auth:
    issuer: "${JWT_ISSUER:kosta-erp-account}"
    audience: "${JWT_AUDIENCE:kosta-erp-api}"
    secret-base64: "${JWT_SECRET_BASE64}"
