global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: eureka-server
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["eureka-server"]
        type: A
        port: 8761
        refresh_interval: 10s

  - job_name: account-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["account-service"]
        type: A
        port: 7071
        refresh_interval: 10s

  - job_name: audit-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["audit-service"]
        type: A
        port: 7072
        refresh_interval: 10s

  - job_name: item-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["item-service"]
        type: A
        port: 7073
        refresh_interval: 10s

  - job_name: inventory-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["inventory-service"]
        type: A
        port: 7074
        refresh_interval: 10s

  - job_name: gateway-server
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["gateway-server"]
        type: A
        port: 7070
        refresh_interval: 10s
